name: Setup Python & Dependencies
description: Install Python, uv and dependencies
runs:
  using: composite
  steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Cache uv
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: uv-${{ hashFiles('pyproject.toml', 'uv.lock') }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Sync dependencies
      run: uv sync --locked --all-extras --dev
      shell: bash

    - name: Generate SECRET_KEY
      id: generate_key
      run: |
        echo "secret_key=$(python -c 'import uuid; print(uuid.uuid4().hex + uuid.uuid4().hex)')" >> $GITHUB_OUTPUT
      shell: bash
