services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"   
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend

  broker:
    image: "rabbitmq:alpine"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 10s
      retries: 5

  result:
    image: "redis:alpine"
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - broker
      - result
    networks:
      - backend

  celery:
    build:
      dockerfile: Dockerfile
      context: .
    command: celery --app=clipboard.celery_app worker --loglevel=info
    volumes:
      - .:/app
      - /app/.venv
    env_file: .env
    depends_on:
      db:
        condition: service_started
      broker:
        condition: service_healthy
      result:
        condition: service_started
    networks:
      - backend 

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery --app=clipboard.celery_app beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=info
    volumes:
      - .:/app
      - /app/.venv
    env_file: .env
    depends_on:
      db:
        condition: service_started
      broker:
        condition: service_healthy
      result:
        condition: service_started
    networks:
      - backend

volumes:
  dbdata:
    name: {{project_name}}_dbdata

networks:
  backend:
    driver: bridge
