services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"   
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend

volumes:
  dbdata:
    name: {{project_name}}_dbdata
    external: true

networks:
  backend:
    driver: bridge
